### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by wbasser** [kevinmehall/usb#2]
Unless I am totally missing something here, I have downloaded the Tessel 2 code as well as the latest USB-master code.  Where in the files is UsbDeviceDescriptor defined at?  THis is in usb_samd.h

**Comment by kevinmehall** [comment]
The UsbDeviceDescriptor structure is defined in the [Atmel headers for the SAMD21](https://github.com/avrxml/sam0). (The name is quite misleading; this is the per-endpoint SRAM data for the USB device controller, not the device descriptor)

If you're trying to build the Tessel 2 firmware both this library and the headers are git submodules -- run `git submodule update --init`

**Comment by wbasser** [comment]
Thanks, I tried searching for it, but no avail.  I've created an Atmel
Studio solution for it.  If you're interested, I would be glad to share
it.  The end goal is just implement the CDC with an interface to a command
line debugger in a project.
