### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by wbasser** [kevinmehall/usb#9]
In 'usb_samd.h', there is a reference to 'extern UsbDeviceDescriptor usb_endpoints[];', however, I cannot find the definition of the variable type 'UsbDeviceScriptor' anywhere in the project?

What am I missing

**Comment by kevinmehall** [comment]
It is included through `io.h` from the device header files from Atmel, either as part of ASF, or I've stashed a copy here: https://github.com/avrxml/sam0

You're presumably already using these headers to be able to do pretty much anything at all with the hardware.
